spring.application.name=Spring-restaurant
spring.datasource.url=jdbc:postgresql://localhost:5432/nom_de_ta_base
spring.datasource.username=ton_utilisateur
spring.datasource.password=ton_mot_de_passe
spring.datasource.driver-class-name=org.postgresql.Driver

spring.sql.init.mode=always

spring.jpa.hibernate.ddl-auto=none

logging.level.org.springframework.jdbc.core.JdbcTemplate=DEBUG